features:
  # Core features
  deviceInfo: true
  listEntities: true
  subscribeStates: true
  
  # Optional features
  subscribeLogs: false
  sensors: true
  
  # Entity types
  binary_sensor: true
  climate: false
  cover: false
  fan: false
  light: false
  switch: false
  text_sensor: true
  number: true 