
jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: verified
name: Validate Homey App
on:
  pull_request:
  push:
  workflow_dispatch:

