// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=.ts,js_import_style=module"
// @generated from file api_options.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MessageOptions, MethodOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api_options.proto.
 */
export const file_api_options: GenFile = /*@__PURE__*/
  fileDesc("ChFhcGlfb3B0aW9ucy5wcm90byIGCgR2b2lkKkYKDUFQSVNvdXJjZVR5cGUSDwoLU09VUkNFX0JPVEgQABIRCg1TT1VSQ0VfU0VSVkVSEAESEQoNU09VUkNFX0NMSUVOVBACOlsKFm5lZWRzX3NldHVwX2Nvbm5lY3Rpb24SHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxiOCCABKAg6BHRydWVSFG5lZWRzU2V0dXBDb25uZWN0aW9uOlgKFG5lZWRzX2F1dGhlbnRpY2F0aW9uEh4uZ29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnMYjwggASgIOgR0cnVlUhNuZWVkc0F1dGhlbnRpY2F0aW9uOjMKAmlkEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGIwIIAEoDToBMFICaWQ6VQoGc291cmNlEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGI0IIAEoDjIOLkFQSVNvdXJjZVR5cGU6C1NPVVJDRV9CT1RIUgZzb3VyY2U6NgoFaWZkZWYSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYjgggASgJUgVpZmRlZjo4CgNsb2cSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYjwggASgIOgR0cnVlUgNsb2c6QgoIbm9fZGVsYXkSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYkAggASgIOgVmYWxzZVIHbm9EZWxheQ", [file_google_protobuf_descriptor]);

/**
 * @generated from message void
 */
export type void$ = Message<"void"> & {
};

/**
 * Describes the message void.
 * Use `create(voidSchema)` to create a new message.
 */
export const voidSchema: GenMessage<void$> = /*@__PURE__*/
  messageDesc(file_api_options, 0);

/**
 * @generated from enum APISourceType
 */
export enum APISourceType {
  /**
   * @generated from enum value: SOURCE_BOTH = 0;
   */
  SOURCE_BOTH = 0,

  /**
   * @generated from enum value: SOURCE_SERVER = 1;
   */
  SOURCE_SERVER = 1,

  /**
   * @generated from enum value: SOURCE_CLIENT = 2;
   */
  SOURCE_CLIENT = 2,
}

/**
 * Describes the enum APISourceType.
 */
export const APISourceTypeSchema: GenEnum<APISourceType> = /*@__PURE__*/
  enumDesc(file_api_options, 0);

/**
 * @generated from extension: optional bool needs_setup_connection = 1038 [default = true];
 */
export const needs_setup_connection: GenExtension<MethodOptions, boolean> = /*@__PURE__*/
  extDesc(file_api_options, 0);

/**
 * @generated from extension: optional bool needs_authentication = 1039 [default = true];
 */
export const needs_authentication: GenExtension<MethodOptions, boolean> = /*@__PURE__*/
  extDesc(file_api_options, 1);

/**
 * @generated from extension: optional uint32 id = 1036 [default = 0];
 */
export const id: GenExtension<MessageOptions, number> = /*@__PURE__*/
  extDesc(file_api_options, 2);

/**
 * @generated from extension: optional APISourceType source = 1037 [default = SOURCE_BOTH];
 */
export const source: GenExtension<MessageOptions, APISourceType> = /*@__PURE__*/
  extDesc(file_api_options, 3);

/**
 * @generated from extension: optional string ifdef = 1038;
 */
export const ifdef: GenExtension<MessageOptions, string> = /*@__PURE__*/
  extDesc(file_api_options, 4);

/**
 * @generated from extension: optional bool log = 1039 [default = true];
 */
export const log: GenExtension<MessageOptions, boolean> = /*@__PURE__*/
  extDesc(file_api_options, 5);

/**
 * @generated from extension: optional bool no_delay = 1040 [default = false];
 */
export const no_delay: GenExtension<MessageOptions, boolean> = /*@__PURE__*/
  extDesc(file_api_options, 6);

