import {
  HelloRequestSchema,
  HelloResponseSchema,
  ConnectRequestSchema,
  ConnectResponseSchema,
  DisconnectRequestSchema,
  DisconnectResponseSchema,
  PingRequestSchema,
  PingResponseSchema,
  DeviceInfoRequestSchema,
  DeviceInfoResponseSchema,
  ListEntitiesRequestSchema,
  ListEntitiesBinarySensorResponseSchema,
  ListEntitiesCoverResponseSchema,
  ListEntitiesFanResponseSchema,
  ListEntitiesLightResponseSchema,
  ListEntitiesSensorResponseSchema,
  ListEntitiesSwitchResponseSchema,
  ListEntitiesTextSensorResponseSchema,
  ListEntitiesDoneResponseSchema,
  SubscribeStatesRequestSchema,
  BinarySensorStateResponseSchema,
  CoverStateResponseSchema,
  FanStateResponseSchema,
  LightStateResponseSchema,
  SensorStateResponseSchema,
  SwitchStateResponseSchema,
  TextSensorStateResponseSchema,
  SubscribeLogsRequestSchema,
  SubscribeLogsResponseSchema,
  CoverCommandRequestSchema,
  FanCommandRequestSchema,
  LightCommandRequestSchema,
  SwitchCommandRequestSchema,
  SubscribeHomeassistantServicesRequestSchema,
  HomeassistantServiceResponseSchema,
  GetTimeRequestSchema,
  GetTimeResponseSchema,
  SubscribeHomeAssistantStatesRequestSchema,
  SubscribeHomeAssistantStateResponseSchema,
  HomeAssistantStateResponseSchema,
  ListEntitiesServicesResponseSchema,
  ExecuteServiceRequestSchema,
  ListEntitiesCameraResponseSchema,
  CameraImageResponseSchema,
  CameraImageRequestSchema,
  ListEntitiesClimateResponseSchema,
  ClimateStateResponseSchema,
  ClimateCommandRequestSchema,
  ListEntitiesNumberResponseSchema,
  NumberStateResponseSchema,
  NumberCommandRequestSchema,
  ListEntitiesSelectResponseSchema,
  SelectStateResponseSchema,
  SelectCommandRequestSchema,
  ListEntitiesLockResponseSchema,
  LockStateResponseSchema,
  LockCommandRequestSchema,
  ListEntitiesButtonResponseSchema,
  ButtonCommandRequestSchema,
  ListEntitiesMediaPlayerResponseSchema,
  MediaPlayerStateResponseSchema,
  MediaPlayerCommandRequestSchema,
  SubscribeBluetoothLEAdvertisementsRequestSchema,
  BluetoothLEAdvertisementResponseSchema,
  BluetoothDeviceRequestSchema,
  BluetoothDeviceConnectionResponseSchema,
  BluetoothGATTGetServicesRequestSchema,
  BluetoothGATTGetServicesResponseSchema,
  BluetoothGATTGetServicesDoneResponseSchema,
  BluetoothGATTReadRequestSchema,
  BluetoothGATTReadResponseSchema,
  BluetoothGATTWriteRequestSchema,
  BluetoothGATTReadDescriptorRequestSchema,
  BluetoothGATTWriteDescriptorRequestSchema,
  BluetoothGATTNotifyRequestSchema,
  BluetoothGATTNotifyDataResponseSchema,
  SubscribeBluetoothConnectionsFreeRequestSchema,
  BluetoothConnectionsFreeResponseSchema,
  BluetoothGATTErrorResponseSchema,
  BluetoothGATTWriteResponseSchema,
  BluetoothGATTNotifyResponseSchema,
  BluetoothDevicePairingResponseSchema,
  BluetoothDeviceUnpairingResponseSchema,
  UnsubscribeBluetoothLEAdvertisementsRequestSchema,
  BluetoothDeviceClearCacheResponseSchema,
  SubscribeVoiceAssistantRequestSchema,
  VoiceAssistantRequestSchema,
  VoiceAssistantResponseSchema,
  VoiceAssistantEventResponseSchema,
  BluetoothLERawAdvertisementsResponseSchema,
  ListEntitiesAlarmControlPanelResponseSchema,
  AlarmControlPanelStateResponseSchema,
  AlarmControlPanelCommandRequestSchema,
  ListEntitiesTextResponseSchema,
  TextStateResponseSchema,
  TextCommandRequestSchema,
  ListEntitiesDateResponseSchema,
  DateStateResponseSchema,
  DateCommandRequestSchema,
  ListEntitiesTimeResponseSchema,
  TimeStateResponseSchema,
  TimeCommandRequestSchema,
  VoiceAssistantAudioSchema,
  ListEntitiesEventResponseSchema,
  EventResponseSchema,
  ListEntitiesValveResponseSchema,
  ValveStateResponseSchema,
  ValveCommandRequestSchema,
  ListEntitiesDateTimeResponseSchema,
  DateTimeStateResponseSchema,
  DateTimeCommandRequestSchema,
  VoiceAssistantTimerEventResponseSchema,
  ListEntitiesUpdateResponseSchema,
  UpdateStateResponseSchema,
  UpdateCommandRequestSchema,
  VoiceAssistantAnnounceRequestSchema,
  VoiceAssistantAnnounceFinishedSchema,
  VoiceAssistantConfigurationRequestSchema,
  VoiceAssistantConfigurationResponseSchema,
  VoiceAssistantSetConfigurationSchema,
  NoiseEncryptionSetKeyRequestSchema,
  NoiseEncryptionSetKeyResponseSchema,
} from '../../protobuf/api_pb.mts';

export enum MessageTypes {
  HelloRequest = 1,
  HelloResponse = 2,
  ConnectRequest = 3,
  ConnectResponse = 4,
  DisconnectRequest = 5,
  DisconnectResponse = 6,
  PingRequest = 7,
  PingResponse = 8,
  DeviceInfoRequest = 9,
  DeviceInfoResponse = 10,
  ListEntitiesRequest = 11,
  ListEntitiesBinarySensorResponse = 12,
  ListEntitiesCoverResponse = 13,
  ListEntitiesFanResponse = 14,
  ListEntitiesLightResponse = 15,
  ListEntitiesSensorResponse = 16,
  ListEntitiesSwitchResponse = 17,
  ListEntitiesTextSensorResponse = 18,
  ListEntitiesDoneResponse = 19,
  SubscribeStatesRequest = 20,
  BinarySensorStateResponse = 21,
  CoverStateResponse = 22,
  FanStateResponse = 23,
  LightStateResponse = 24,
  SensorStateResponse = 25,
  SwitchStateResponse = 26,
  TextSensorStateResponse = 27,
  SubscribeLogsRequest = 28,
  SubscribeLogsResponse = 29,
  CoverCommandRequest = 30,
  FanCommandRequest = 31,
  LightCommandRequest = 32,
  SwitchCommandRequest = 33,
  SubscribeHomeassistantServicesRequest = 34,
  HomeassistantServiceResponse = 35,
  GetTimeRequest = 36,
  GetTimeResponse = 37,
  SubscribeHomeAssistantStatesRequest = 38,
  SubscribeHomeAssistantStateResponse = 39,
  HomeAssistantStateResponse = 40,
  ListEntitiesServicesResponse = 41,
  ExecuteServiceRequest = 42,
  ListEntitiesCameraResponse = 43,
  CameraImageResponse = 44,
  CameraImageRequest = 45,
  ListEntitiesClimateResponse = 46,
  ClimateStateResponse = 47,
  ClimateCommandRequest = 48,
  ListEntitiesNumberResponse = 49,
  NumberStateResponse = 50,
  NumberCommandRequest = 51,
  ListEntitiesSelectResponse = 52,
  SelectStateResponse = 53,
  SelectCommandRequest = 54,
  ListEntitiesLockResponse = 55,
  LockStateResponse = 56,
  LockCommandRequest = 57,
  ListEntitiesButtonResponse = 58,
  ButtonCommandRequest = 59,
  ListEntitiesMediaPlayerResponse = 60,
  MediaPlayerStateResponse = 61,
  MediaPlayerCommandRequest = 62,
  SubscribeBluetoothLEAdvertisementsRequest = 63,
  BluetoothLEAdvertisementResponse = 64,
  BluetoothDeviceRequest = 65,
  BluetoothDeviceConnectionResponse = 66,
  BluetoothGATTGetServicesRequest = 67,
  BluetoothGATTGetServicesResponse = 68,
  BluetoothGATTGetServicesDoneResponse = 69,
  BluetoothGATTReadRequest = 70,
  BluetoothGATTReadResponse = 71,
  BluetoothGATTWriteRequest = 72,
  BluetoothGATTReadDescriptorRequest = 73,
  BluetoothGATTWriteDescriptorRequest = 74,
  BluetoothGATTNotifyRequest = 75,
  BluetoothGATTNotifyDataResponse = 76,
  SubscribeBluetoothConnectionsFreeRequest = 77,
  BluetoothConnectionsFreeResponse = 78,
  BluetoothGATTErrorResponse = 79,
  BluetoothGATTWriteResponse = 80,
  BluetoothGATTNotifyResponse = 81,
  BluetoothDevicePairingResponse = 82,
  BluetoothDeviceUnpairingResponse = 83,
  UnsubscribeBluetoothLEAdvertisementsRequest = 84,
  BluetoothDeviceClearCacheResponse = 85,
  SubscribeVoiceAssistantRequest = 86,
  VoiceAssistantRequest = 87,
  VoiceAssistantResponse = 88,
  VoiceAssistantEventResponse = 89,
  BluetoothLERawAdvertisementsResponse = 90,
  ListEntitiesAlarmControlPanelResponse = 91,
  AlarmControlPanelStateResponse = 92,
  AlarmControlPanelCommandRequest = 93,
  ListEntitiesTextResponse = 94,
  TextStateResponse = 95,
  TextCommandRequest = 96,
  ListEntitiesDateResponse = 97,
  DateStateResponse = 98,
  DateCommandRequest = 99,
  ListEntitiesTimeResponse = 100,
  TimeStateResponse = 101,
  TimeCommandRequest = 102,
  VoiceAssistantAudio = 103,
  ListEntitiesEventResponse = 104,
  EventResponse = 105,
  ListEntitiesValveResponse = 106,
  ValveStateResponse = 107,
  ValveCommandRequest = 108,
  ListEntitiesDateTimeResponse = 109,
  DateTimeStateResponse = 110,
  DateTimeCommandRequest = 111,
  VoiceAssistantTimerEventResponse = 112,
  ListEntitiesUpdateResponse = 113,
  UpdateStateResponse = 114,
  UpdateCommandRequest = 115,
  VoiceAssistantAnnounceRequest = 116,
  VoiceAssistantAnnounceFinished = 117,
  VoiceAssistantConfigurationRequest = 118,
  VoiceAssistantConfigurationResponse = 119,
  VoiceAssistantSetConfiguration = 120,
  NoiseEncryptionSetKeyRequest = 121,
  NoiseEncryptionSetKeyResponse = 122,
}

export const SUBSCRIBE_STATES_RESPONSE_TYPES = [
  MessageTypes.BinarySensorStateResponse,
  MessageTypes.CoverStateResponse,
  MessageTypes.FanStateResponse,
  MessageTypes.LightStateResponse,
  MessageTypes.SensorStateResponse,
  MessageTypes.SwitchStateResponse,
  MessageTypes.TextSensorStateResponse,
  MessageTypes.ClimateStateResponse,
  MessageTypes.NumberStateResponse,
  MessageTypes.SelectStateResponse,
  MessageTypes.LockStateResponse,
  MessageTypes.MediaPlayerStateResponse,
  MessageTypes.AlarmControlPanelStateResponse,
  MessageTypes.TextStateResponse,
  MessageTypes.DateStateResponse,
  MessageTypes.TimeStateResponse,
  MessageTypes.DateTimeStateResponse,
  MessageTypes.UpdateStateResponse,
] as const;

export const MESSAGE_TYPE_TO_PROTO: Record<number, any> = {
  [MessageTypes.HelloRequest]: HelloRequestSchema,
  [MessageTypes.HelloResponse]: HelloResponseSchema,
  [MessageTypes.ConnectRequest]: ConnectRequestSchema,
  [MessageTypes.ConnectResponse]: ConnectResponseSchema,
  [MessageTypes.DisconnectRequest]: DisconnectRequestSchema,
  [MessageTypes.DisconnectResponse]: DisconnectResponseSchema,
  [MessageTypes.PingRequest]: PingRequestSchema,
  [MessageTypes.PingResponse]: PingResponseSchema,
  [MessageTypes.DeviceInfoRequest]: DeviceInfoRequestSchema,
  [MessageTypes.DeviceInfoResponse]: DeviceInfoResponseSchema,
  [MessageTypes.ListEntitiesRequest]: ListEntitiesRequestSchema,
  [MessageTypes.ListEntitiesBinarySensorResponse]: ListEntitiesBinarySensorResponseSchema,
  [MessageTypes.ListEntitiesCoverResponse]: ListEntitiesCoverResponseSchema,
  [MessageTypes.ListEntitiesFanResponse]: ListEntitiesFanResponseSchema,
  [MessageTypes.ListEntitiesLightResponse]: ListEntitiesLightResponseSchema,
  [MessageTypes.ListEntitiesSensorResponse]: ListEntitiesSensorResponseSchema,
  [MessageTypes.ListEntitiesSwitchResponse]: ListEntitiesSwitchResponseSchema,
  [MessageTypes.ListEntitiesTextSensorResponse]: ListEntitiesTextSensorResponseSchema,
  [MessageTypes.ListEntitiesDoneResponse]: ListEntitiesDoneResponseSchema,
  [MessageTypes.SubscribeStatesRequest]: SubscribeStatesRequestSchema,
  [MessageTypes.BinarySensorStateResponse]: BinarySensorStateResponseSchema,
  [MessageTypes.CoverStateResponse]: CoverStateResponseSchema,
  [MessageTypes.FanStateResponse]: FanStateResponseSchema,
  [MessageTypes.LightStateResponse]: LightStateResponseSchema,
  [MessageTypes.SensorStateResponse]: SensorStateResponseSchema,
  [MessageTypes.SwitchStateResponse]: SwitchStateResponseSchema,
  [MessageTypes.TextSensorStateResponse]: TextSensorStateResponseSchema,
  [MessageTypes.SubscribeLogsRequest]: SubscribeLogsRequestSchema,
  [MessageTypes.SubscribeLogsResponse]: SubscribeLogsResponseSchema,
  [MessageTypes.CoverCommandRequest]: CoverCommandRequestSchema,
  [MessageTypes.FanCommandRequest]: FanCommandRequestSchema,
  [MessageTypes.LightCommandRequest]: LightCommandRequestSchema,
  [MessageTypes.SwitchCommandRequest]: SwitchCommandRequestSchema,
  [MessageTypes.SubscribeHomeassistantServicesRequest]: SubscribeHomeassistantServicesRequestSchema,
  [MessageTypes.HomeassistantServiceResponse]: HomeassistantServiceResponseSchema,
  [MessageTypes.GetTimeRequest]: GetTimeRequestSchema,
  [MessageTypes.GetTimeResponse]: GetTimeResponseSchema,
  [MessageTypes.SubscribeHomeAssistantStatesRequest]: SubscribeHomeAssistantStatesRequestSchema,
  [MessageTypes.SubscribeHomeAssistantStateResponse]: SubscribeHomeAssistantStateResponseSchema,
  [MessageTypes.HomeAssistantStateResponse]: HomeAssistantStateResponseSchema,
  [MessageTypes.ListEntitiesServicesResponse]: ListEntitiesServicesResponseSchema,
  [MessageTypes.ExecuteServiceRequest]: ExecuteServiceRequestSchema,
  [MessageTypes.ListEntitiesCameraResponse]: ListEntitiesCameraResponseSchema,
  [MessageTypes.CameraImageResponse]: CameraImageResponseSchema,
  [MessageTypes.CameraImageRequest]: CameraImageRequestSchema,
  [MessageTypes.ListEntitiesClimateResponse]: ListEntitiesClimateResponseSchema,
  [MessageTypes.ClimateStateResponse]: ClimateStateResponseSchema,
  [MessageTypes.ClimateCommandRequest]: ClimateCommandRequestSchema,
  [MessageTypes.ListEntitiesNumberResponse]: ListEntitiesNumberResponseSchema,
  [MessageTypes.NumberStateResponse]: NumberStateResponseSchema,
  [MessageTypes.NumberCommandRequest]: NumberCommandRequestSchema,
  [MessageTypes.ListEntitiesSelectResponse]: ListEntitiesSelectResponseSchema,
  [MessageTypes.SelectStateResponse]: SelectStateResponseSchema,
  [MessageTypes.SelectCommandRequest]: SelectCommandRequestSchema,
  [MessageTypes.ListEntitiesLockResponse]: ListEntitiesLockResponseSchema,
  [MessageTypes.LockStateResponse]: LockStateResponseSchema,
  [MessageTypes.LockCommandRequest]: LockCommandRequestSchema,
  [MessageTypes.ListEntitiesButtonResponse]: ListEntitiesButtonResponseSchema,
  [MessageTypes.ButtonCommandRequest]: ButtonCommandRequestSchema,
  [MessageTypes.ListEntitiesMediaPlayerResponse]: ListEntitiesMediaPlayerResponseSchema,
  [MessageTypes.MediaPlayerStateResponse]: MediaPlayerStateResponseSchema,
  [MessageTypes.MediaPlayerCommandRequest]: MediaPlayerCommandRequestSchema,
  [MessageTypes.SubscribeBluetoothLEAdvertisementsRequest]: SubscribeBluetoothLEAdvertisementsRequestSchema,
  [MessageTypes.BluetoothLEAdvertisementResponse]: BluetoothLEAdvertisementResponseSchema,
  [MessageTypes.BluetoothDeviceRequest]: BluetoothDeviceRequestSchema,
  [MessageTypes.BluetoothDeviceConnectionResponse]: BluetoothDeviceConnectionResponseSchema,
  [MessageTypes.BluetoothGATTGetServicesRequest]: BluetoothGATTGetServicesRequestSchema,
  [MessageTypes.BluetoothGATTGetServicesResponse]: BluetoothGATTGetServicesResponseSchema,
  [MessageTypes.BluetoothGATTGetServicesDoneResponse]: BluetoothGATTGetServicesDoneResponseSchema,
  [MessageTypes.BluetoothGATTReadRequest]: BluetoothGATTReadRequestSchema,
  [MessageTypes.BluetoothGATTReadResponse]: BluetoothGATTReadResponseSchema,
  [MessageTypes.BluetoothGATTWriteRequest]: BluetoothGATTWriteRequestSchema,
  [MessageTypes.BluetoothGATTReadDescriptorRequest]: BluetoothGATTReadDescriptorRequestSchema,
  [MessageTypes.BluetoothGATTWriteDescriptorRequest]: BluetoothGATTWriteDescriptorRequestSchema,
  [MessageTypes.BluetoothGATTNotifyRequest]: BluetoothGATTNotifyRequestSchema,
  [MessageTypes.BluetoothGATTNotifyDataResponse]: BluetoothGATTNotifyDataResponseSchema,
  [MessageTypes.SubscribeBluetoothConnectionsFreeRequest]: SubscribeBluetoothConnectionsFreeRequestSchema,
  [MessageTypes.BluetoothConnectionsFreeResponse]: BluetoothConnectionsFreeResponseSchema,
  [MessageTypes.BluetoothGATTErrorResponse]: BluetoothGATTErrorResponseSchema,
  [MessageTypes.BluetoothGATTWriteResponse]: BluetoothGATTWriteResponseSchema,
  [MessageTypes.BluetoothGATTNotifyResponse]: BluetoothGATTNotifyResponseSchema,
  [MessageTypes.BluetoothDevicePairingResponse]: BluetoothDevicePairingResponseSchema,
  [MessageTypes.BluetoothDeviceUnpairingResponse]: BluetoothDeviceUnpairingResponseSchema,
  [MessageTypes.UnsubscribeBluetoothLEAdvertisementsRequest]: UnsubscribeBluetoothLEAdvertisementsRequestSchema,
  [MessageTypes.BluetoothDeviceClearCacheResponse]: BluetoothDeviceClearCacheResponseSchema,
  [MessageTypes.SubscribeVoiceAssistantRequest]: SubscribeVoiceAssistantRequestSchema,
  [MessageTypes.VoiceAssistantRequest]: VoiceAssistantRequestSchema,
  [MessageTypes.VoiceAssistantResponse]: VoiceAssistantResponseSchema,
  [MessageTypes.VoiceAssistantEventResponse]: VoiceAssistantEventResponseSchema,
  [MessageTypes.BluetoothLERawAdvertisementsResponse]: BluetoothLERawAdvertisementsResponseSchema,
  [MessageTypes.ListEntitiesAlarmControlPanelResponse]: ListEntitiesAlarmControlPanelResponseSchema,
  [MessageTypes.AlarmControlPanelStateResponse]: AlarmControlPanelStateResponseSchema,
  [MessageTypes.AlarmControlPanelCommandRequest]: AlarmControlPanelCommandRequestSchema,
  [MessageTypes.ListEntitiesTextResponse]: ListEntitiesTextResponseSchema,
  [MessageTypes.TextStateResponse]: TextStateResponseSchema,
  [MessageTypes.TextCommandRequest]: TextCommandRequestSchema,
  [MessageTypes.ListEntitiesDateResponse]: ListEntitiesDateResponseSchema,
  [MessageTypes.DateStateResponse]: DateStateResponseSchema,
  [MessageTypes.DateCommandRequest]: DateCommandRequestSchema,
  [MessageTypes.ListEntitiesTimeResponse]: ListEntitiesTimeResponseSchema,
  [MessageTypes.TimeStateResponse]: TimeStateResponseSchema,
  [MessageTypes.TimeCommandRequest]: TimeCommandRequestSchema,
  [MessageTypes.VoiceAssistantAudio]: VoiceAssistantAudioSchema,
  [MessageTypes.ListEntitiesEventResponse]: ListEntitiesEventResponseSchema,
  [MessageTypes.EventResponse]: EventResponseSchema,
  [MessageTypes.ListEntitiesValveResponse]: ListEntitiesValveResponseSchema,
  [MessageTypes.ValveStateResponse]: ValveStateResponseSchema,
  [MessageTypes.ValveCommandRequest]: ValveCommandRequestSchema,
  [MessageTypes.ListEntitiesDateTimeResponse]: ListEntitiesDateTimeResponseSchema,
  [MessageTypes.DateTimeStateResponse]: DateTimeStateResponseSchema,
  [MessageTypes.DateTimeCommandRequest]: DateTimeCommandRequestSchema,
  [MessageTypes.VoiceAssistantTimerEventResponse]: VoiceAssistantTimerEventResponseSchema,
  [MessageTypes.ListEntitiesUpdateResponse]: ListEntitiesUpdateResponseSchema,
  [MessageTypes.UpdateStateResponse]: UpdateStateResponseSchema,
  [MessageTypes.UpdateCommandRequest]: UpdateCommandRequestSchema,
  [MessageTypes.VoiceAssistantAnnounceRequest]: VoiceAssistantAnnounceRequestSchema,
  [MessageTypes.VoiceAssistantAnnounceFinished]: VoiceAssistantAnnounceFinishedSchema,
  [MessageTypes.VoiceAssistantConfigurationRequest]: VoiceAssistantConfigurationRequestSchema,
  [MessageTypes.VoiceAssistantConfigurationResponse]: VoiceAssistantConfigurationResponseSchema,
  [MessageTypes.VoiceAssistantSetConfiguration]: VoiceAssistantSetConfigurationSchema,
  [MessageTypes.NoiseEncryptionSetKeyRequest]: NoiseEncryptionSetKeyRequestSchema,
  [MessageTypes.NoiseEncryptionSetKeyResponse]: NoiseEncryptionSetKeyResponseSchema,
};

export const MESSAGE_NUMBER_TO_PROTO = Object.values(MESSAGE_TYPE_TO_PROTO); 